name: Output information
on: workflow_dispatch
jobs: 
  info: 
    runs-on: ubuntu-latest
    steps: 
      - name: Output issues context
        run: echo "${{ toJSON(issues) }}"
      - name: Output GitHub context
        run: echo "${{ toJSON(github) }}" 